sudo: false
language: python
addons:
  homebrew:
    brewfile: true
  apt:
    sources: ['llvm-toolchain-xenial-6.0', 'ubuntu-toolchain-r-test']
    packages:
      - llvm-6.0
      - llvm-6.0-dev
      - g++-5
jobs:
  include:

    # LINUX

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o regression -t long,python,llvm,gcc,z3,qemu,cparser"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o example -t long,python,llvm,gcc,z3,qemu,cparser"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o long"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o qemu -t llvm,gcc"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o qemu -t python,gcc"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o qemu -t python,llvm"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o llvm -t qemu,long"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o gcc -t qemu,long"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o python -t qemu,long"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o z3"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_TEST_EXTRA_ARG="-o cparser"

    - os: linux
      python: 3.8
      env:
       - CXX=g++-5 LLVM_CONFIG=llvm-config-6.0
       - MIASM_EXTENTED_TESTS="ls_x64"



    # OSX
    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o regression -t long,python,llvm,gcc,z3,qemu,cparser"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o example -t long,python,llvm,gcc,z3,qemu,cparser"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o long"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o qemu -t llvm,gcc"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o qemu -t python,gcc"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o qemu -t python,llvm"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o llvm -t qemu,long"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o gcc -t qemu,long"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o python -t qemu,long"

    #    - os: osx
    #      language: generic
    #      env:
    #       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
    #       - MIASM_TEST_EXTRA_ARG="-o z3"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_TEST_EXTRA_ARG="-o cparser"

    - os: osx
      language: generic
      env:
       - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
       - MIASM_EXTENTED_TESTS="ls_x64"


install:
   - pip install --user codespell && git ls-files | xargs codespell --ignore-words=.codespell_ignore 2>/dev/null
   # install
   - python setup.py build build_ext
   - python setup.py install --user
   # extended tests
   - git clone https://github.com/cea-sec/miasm-extended-tests

# before_script:
# #- pip install --user -r requirements.txt
# #- pip install --user -r optional_requirements.txt
# # codespell
# - "pip install --user codespell && git ls-files | xargs codespell --ignore-words=.codespell_ignore 2>/dev/null"
# # install
# - python setup.py build build_ext
# - python setup.py install --user
# # extended tests
# - git clone https://github.com/cea-sec/miasm-extended-tests
script:
  - test -z "$MIASM_TEST_EXTRA_ARG" || (cd test && flags=""; python --version | grep -q "Python 3" || flags="-W error"; python $flags test_all.py $MIASM_TEST_EXTRA_ARG && git ls-files -o --exclude-standard)
  - test -z "$MIASM_EXTENTED_TESTS" || (cd "miasm-extended-tests/$MIASM_EXTENTED_TESTS" && ./run.sh "$TRAVIS_BUILD_DIR")
